/**
 * Error codes for the LabLoop Healthcare System
 */

export const ERROR_CODES = {
  // Authentication & Authorization
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_USER_DISABLED: 'AUTH_USER_DISABLED',

  // Validation
  VALIDATION_REQUIRED_FIELD: 'VALIDATION_REQUIRED_FIELD',
  VALIDATION_INVALID_FORMAT: 'VALIDATION_INVALID_FORMAT',
  VALIDATION_INVALID_VALUE: 'VALIDATION_INVALID_VALUE',
  VALIDATION_DUPLICATE_VALUE: 'VALIDATION_DUPLICATE_VALUE',

  // Resource Management
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_IN_USE: 'RESOURCE_IN_USE',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',

  // Business Logic - Patient Management
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  PATIENT_ALREADY_EXISTS: 'PATIENT_ALREADY_EXISTS',
  PATIENT_INVALID_ID: 'PATIENT_INVALID_ID',

  // Business Logic - Case Management
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  CASE_INVALID_STATUS: 'CASE_INVALID_STATUS',
  CASE_CANNOT_UPDATE: 'CASE_CANNOT_UPDATE',
  CASE_MISSING_SAMPLES: 'CASE_MISSING_SAMPLES',

  // Business Logic - Sample Management
  SAMPLE_NOT_FOUND: 'SAMPLE_NOT_FOUND',
  SAMPLE_INVALID_STATUS: 'SAMPLE_INVALID_STATUS',
  SAMPLE_ALREADY_PROCESSED: 'SAMPLE_ALREADY_PROCESSED',

  // Business Logic - Test Management
  TEST_NOT_FOUND: 'TEST_NOT_FOUND',
  TEST_NOT_AVAILABLE: 'TEST_NOT_AVAILABLE',
  TEST_INVALID_PARAMETERS: 'TEST_INVALID_PARAMETERS',

  // Database
  DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
  DATABASE_QUERY_ERROR: 'DATABASE_QUERY_ERROR',
  DATABASE_TRANSACTION_ERROR: 'DATABASE_TRANSACTION_ERROR',

  // External Services
  EXTERNAL_SERVICE_UNAVAILABLE: 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
  SMS_SEND_FAILED: 'SMS_SEND_FAILED',

  // System
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];